openapi: 3.0.1
info:
  description: "<h2>Getting started</h2><p>Localizely API is built on <a href=\"https://en.wikipedia.org/wiki/Representational_state_transfer\"\
    \ target=\"_blank\">REST</a>. <br>You can use this API for importing & exporting\
    \ your localization files in order to automate the process with `curl` scripts\
    \ or external <a href=\"https://en.wikipedia.org/wiki/Continuous_integration\"\
    \ target=\"_blank\">CI</a> tools. <br>Response is returned in JSON form even in\
    \ case of error. <br></p><p>If you Authenticate with your API token on this page\
    \ by clicking \"Authorize\" button, you can make API calls directly from here\
    \ with \"Try it out\", and generate such `curl` examples. </p><h2>API Authentication</h2><p>Authenticate\
    \ your account by sending your API token as a request header `X-Api-Token`. <br>The\
    \ token can be found under <a href=\"https://app.localizely.com/account\" target=\"\
    _blank\">My Profile</a> page. <br>A user must have an Admin role in the project\
    \ in order to access the project with his token. <br>API requests without authentication\
    \ will fail.</p><p><b>Base url:</b> `https://api.localizely.com`</p>"
  termsOfService: https://localizely.com/terms-of-service/
  title: Localizely API
  version: 1.2.1
servers:
- description: Generated server url
  url: https://api.localizely.com
paths:
  /v1/projects/{project_id}/files/upload:
    post:
      operationId: importLocalizationFile
      parameters:
      - description: Project ID - Can be found on 'My projects' page
        explode: false
        in: path
        name: project_id
        required: true
        schema:
          type: string
        style: simple
      - description: Name of the branch to upload file into. Only in case of activated
          branching feature.
        explode: true
        in: query
        name: branch
        required: false
        schema:
          type: string
        style: form
      - description: "Language to upload, specified as language code. e.g. `en`, `en_GB`\
          \ or `en-GB`"
        explode: true
        in: query
        name: lang_code
        required: true
        schema:
          type: string
        style: form
      - description: If translation in given language should be overwritten with modified
          translation from uploading file.
        explode: true
        in: query
        name: overwrite
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: "If uploading translations, that are added, should be marked\
          \ as Reviewed. For uploading translations that are only modified it will\
          \ have effect only if `overwrite` is set to `true`."
        explode: true
        in: query
        name: reviewed
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: "Optional list of tags to add to new translations from uploading\
          \ file. <br><br>Multiple tags can be defined in a following way: `&tag_added_keys=NEW&tag_added_keys=NEW_SPRINT05`"
        explode: true
        in: query
        name: tag_added
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "Optional list of tags to add to updated translations from uploading\
          \ file. <br><br>Multiple tags can be defined in a following way: `&tag_updated_keys=UPDATED&tag_updated_keys=UPDATED_SPRINT05`"
        explode: true
        in: query
        name: tag_updated
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "Optional list of tags to add to removed translations from uploading\
          \ file. <br><br>Multiple tags can be defined in a following way: `&tag_removed_keys=REMOVED&tag_removed_keys=REMOVED_SPRINT05`"
        explode: true
        in: query
        name: tag_removed
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/importLocalizationFile_request'
      responses:
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/InvalidImportFileErrorDto'
          description: |-
            Error codes:<br />&nbsp;<br />- `invalid_import_file` when file invalid. Returned with `errors` list<br />- `max_upload_size_exceeded` when uploading file exceeds size limit<br />- `upgrade_required` when uploading more string keys than accepted by owner's account plan limit<br />- `projects_limit_read_only` when project is in read-only state due to exceeded projects limit
            `'bad_request'` when request generally is not well formed
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Not Found
        "200":
          description: "OK, file uploaded"
      security:
      - API auth: []
      summary: Upload translations for a language
      tags:
      - Upload API
  /v1/projects/{project_id}/branches/{branch}:
    post:
      operationId: createBranch
      parameters:
      - description: Project ID - Can be found on 'My projects' page
        explode: false
        in: path
        name: project_id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: Name of the branch to be created
        explode: false
        in: path
        name: branch
        required: true
        schema:
          maxLength: 200
          minLength: 0
          type: string
        style: simple
      - description: Name of the source branch from which new branch will be created
        explode: true
        in: query
        name: source_branch
        required: true
        schema:
          type: string
        style: form
      responses:
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Error codes:<br />&nbsp;<br />- `bad_request` when request
            generally is not well formed<br />- `limit_reached` when project already
            has max allowed number of branches<br />- `projects_limit_read_only` when
            project is in read-only state due to exceeded projects limit
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Not Found
        "200":
          description: "OK, created"
      security:
      - API auth: []
      summary: Create a new branch
      tags:
      - Branch API
  /v1/projects/{project_id}/status:
    get:
      operationId: getTranslationStatus
      parameters:
      - description: Project ID - Can be found on 'My projects' page
        explode: false
        in: path
        name: project_id
        required: true
        schema:
          type: string
        style: simple
      - description: Name of the branch to get translation status for. Only in case
          of activated branching feature.
        explode: true
        in: query
        name: branch
        required: false
        schema:
          type: string
        style: form
      responses:
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Error codes:<br />&nbsp;<br />- `bad_request` when request
            generally is not well formed
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Not Found
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProjectStatusDto'
          description: "OK, data returned"
      security:
      - API auth: []
      summary: Get Translation Status for the project
      tags:
      - Translation Status API
  /v1/projects/{project_id}/files/download:
    get:
      description: "<b>Note:</b> This endpoint is intended for getting translation\
        \ files to your source-code. This endpoint should not be called directly from\
        \ you app in runtime, as it has <b>rate-limiting</b>. <br/>For over-the-air\
        \ translation updates please consider using our <a href=\"https://localizely.com/flutter-over-the-air/\"\
        \ target=\"_blank\">SDK for Flutter</a> or <a href=\"https://localizely.com/aws-s3-integration/\"\
        \ target=\"_blank\">integrate with AWS S3 bucket</a>."
      operationId: getLocalizationFile
      parameters:
      - description: Project ID - Can be found on 'My projects' page
        explode: false
        in: path
        name: project_id
        required: true
        schema:
          type: string
        style: simple
      - description: Name of the branch to download file from. Only in case of activated
          branching feature.
        explode: true
        in: query
        name: branch
        required: false
        schema:
          type: string
        style: form
      - description: "Language to download, specified as language code. e.g. `en`,\
          \ `en_GB` or `en-GB`. For multiple languages use comma separator. If omitted,\
          \ all languages are downloaded."
        explode: true
        in: query
        name: lang_codes
        required: false
        schema:
          type: string
        style: form
      - description: File format
        explode: true
        in: query
        name: type
        required: true
        schema:
          enum:
          - android_xml
          - ios_strings
          - ios_stringsdict
          - java_properties
          - rails_yaml
          - angular_xlf
          - flutter_arb
          - dotnet_resx
          - po
          - pot
          - json
          - csv
          - xlsx
          type: string
        style: form
      - description: (Only for Java .properties files download) Character encoding.
          Default is `latin_1`.
        explode: true
        in: query
        name: java_properties_encoding
        required: false
        schema:
          enum:
          - utf_8
          - latin_1
          type: string
        style: form
      - description: "Optional list of tags to be downloaded. <br>If not set, all\
          \ string keys will be considered for download. <br><br>Multiple tags can\
          \ be defined in a following way: `&include_tags=ANDROID&include_tags=ANDROID_SPRINT05`."
        explode: true
        in: query
        name: include_tags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "Optional list of tags to be excluded from download. <br>If not\
          \ set, all string keys will be considered for download. <br><br> Multiple\
          \ tags can be defined in a following way: `&exclude_tags=REMOVED&exclude_tags=REMOVED_SPRINT05`."
        explode: true
        in: query
        name: exclude_tags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "Optional. How you would like empty translations to be exported.\
          \ Allowed values are `empty` to keep empty, `main` to replace with the main\
          \ language value, or `skip` to omit."
        explode: true
        in: query
        name: export_empty_as
        required: false
        schema:
          default: empty
          enum:
          - empty
          - main
          - skip
          type: string
        style: form
      responses:
        "400":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Error codes:<br />&nbsp;<br />- `invalid_export_data_rails_yaml`
            when data collision for yaml download<br />- `bad_request` when request
            generally is not well formed
        "404":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ErrorDto'
          description: Not Found
        "200":
          description: "OK, file returned"
      security:
      - API auth: []
      summary: Download translations for a language in a specified file format
      tags:
      - Download API
components:
  schemas:
    ErrorDto:
      example:
        errorMessage: errorMessage
        errorCode: already_exists
        errorData:
          key: "{}"
      properties:
        errorCode:
          enum:
          - already_exists
          - too_long
          - too_many_requests
          - bad_request
          - not_configured
          - bad_captcha
          - bad_turnstile
          - bad_url
          - confirmation_invalid
          - forbidden_email
          - main_locale_invalid
          - branching_disabled
          - not_activated
          - invalid_password
          - invalid_import_file
          - invalid_export_data_rails_yaml
          - forbidden
          - internal_error
          - not_found
          - upgrade_required
          - subscription_change_disabled_in_past_due
          - subscription_creation_still_processing
          - order_creation_still_processing
          - branching_not_supported
          - ota_not_supported
          - string_keys_limit
          - projects_limit
          - projects_limit_read_only
          - limit_reached
          - import_keys_limit_exceeded
          - max_upload_size_exceeded
          - prevention_limit_reached
          - tags_prevention_limit_reached
          - string_key_not_found
          - merge_outdated
          - mt_locale_not_supported
          - mt_main_translation_empty
          - mt_main_translation_not_supported
          - mt_source_translation_too_long
          - mt_chars_missing
          - mt_no_selected_strings
          - tm_upload_file_invalid
          - tm_upload_file_max_entries_exceeded
          - tm_upload_file_version_not_supported
          - tm_max_total_entries_exceeded
          - tm_max_total_memories_exceeded
          - glossary_locale_cant_remove
          - glossary_upload_file_invalid
          - glossary_upload_file_column_separator_invalid
          - glossary_upload_file_headers_invalid
          - glossary_upload_file_max_terms_exceeded
          - glossary_max_total_terms_exceeded
          - glossary_max_total_glossaries_exceeded
          - order_oversize
          - github_not_supported
          - github_token_invalid
          - github_token_scope_invalid
          - github_url_invalid
          - github_branch_invalid
          - github_repo_invalid
          - github_config_file_missing
          - github_config_file_invalid
          - github_push_no_changes
          - gitlab_not_supported
          - gitlab_token_invalid
          - gitlab_token_scope_invalid
          - gitlab_url_invalid
          - gitlab_branch_invalid
          - gitlab_repo_invalid
          - gitlab_config_file_missing
          - gitlab_config_file_invalid
          - gitlab_push_no_changes
          - bitbucket_not_supported
          - bitbucket_token_invalid
          - bitbucket_token_scope_invalid
          - bitbucket_url_invalid
          - bitbucket_branch_invalid
          - bitbucket_repo_invalid
          - bitbucket_config_file_missing
          - bitbucket_config_file_invalid
          - bitbucket_push_no_changes
          - aws_s3_not_supported
          - aws_s3_credentials_invalid
          - aws_s3_permissions_invalid
          - aws_s3_bucket_invalid
          - aws_s3_region_invalid
          - expired
          - unauthorized
          - unexpected_error
          - service_unavailable
          type: string
        errorMessage:
          type: string
        errorData:
          additionalProperties:
            type: object
          type: object
      type: object
    ImportFileError:
      example:
        line: 0
        errorMessage: errorMessage
        position: 6
      properties:
        line:
          format: int32
          type: integer
        position:
          format: int32
          type: integer
        errorMessage:
          type: string
      type: object
    InvalidImportFileErrorDto:
      example:
        errorMessage: errorMessage
        errorCode: already_exists
        errorData:
          key: "{}"
        errors:
        - line: 0
          errorMessage: errorMessage
          position: 6
        - line: 0
          errorMessage: errorMessage
          position: 6
      properties:
        errorCode:
          enum:
          - already_exists
          - too_long
          - too_many_requests
          - bad_request
          - not_configured
          - bad_captcha
          - bad_turnstile
          - bad_url
          - confirmation_invalid
          - forbidden_email
          - main_locale_invalid
          - branching_disabled
          - not_activated
          - invalid_password
          - invalid_import_file
          - invalid_export_data_rails_yaml
          - forbidden
          - internal_error
          - not_found
          - upgrade_required
          - subscription_change_disabled_in_past_due
          - subscription_creation_still_processing
          - order_creation_still_processing
          - branching_not_supported
          - ota_not_supported
          - string_keys_limit
          - projects_limit
          - projects_limit_read_only
          - limit_reached
          - import_keys_limit_exceeded
          - max_upload_size_exceeded
          - prevention_limit_reached
          - tags_prevention_limit_reached
          - string_key_not_found
          - merge_outdated
          - mt_locale_not_supported
          - mt_main_translation_empty
          - mt_main_translation_not_supported
          - mt_source_translation_too_long
          - mt_chars_missing
          - mt_no_selected_strings
          - tm_upload_file_invalid
          - tm_upload_file_max_entries_exceeded
          - tm_upload_file_version_not_supported
          - tm_max_total_entries_exceeded
          - tm_max_total_memories_exceeded
          - glossary_locale_cant_remove
          - glossary_upload_file_invalid
          - glossary_upload_file_column_separator_invalid
          - glossary_upload_file_headers_invalid
          - glossary_upload_file_max_terms_exceeded
          - glossary_max_total_terms_exceeded
          - glossary_max_total_glossaries_exceeded
          - order_oversize
          - github_not_supported
          - github_token_invalid
          - github_token_scope_invalid
          - github_url_invalid
          - github_branch_invalid
          - github_repo_invalid
          - github_config_file_missing
          - github_config_file_invalid
          - github_push_no_changes
          - gitlab_not_supported
          - gitlab_token_invalid
          - gitlab_token_scope_invalid
          - gitlab_url_invalid
          - gitlab_branch_invalid
          - gitlab_repo_invalid
          - gitlab_config_file_missing
          - gitlab_config_file_invalid
          - gitlab_push_no_changes
          - bitbucket_not_supported
          - bitbucket_token_invalid
          - bitbucket_token_scope_invalid
          - bitbucket_url_invalid
          - bitbucket_branch_invalid
          - bitbucket_repo_invalid
          - bitbucket_config_file_missing
          - bitbucket_config_file_invalid
          - bitbucket_push_no_changes
          - aws_s3_not_supported
          - aws_s3_credentials_invalid
          - aws_s3_permissions_invalid
          - aws_s3_bucket_invalid
          - aws_s3_region_invalid
          - expired
          - unauthorized
          - unexpected_error
          - service_unavailable
          type: string
        errorMessage:
          type: string
        errorData:
          additionalProperties:
            type: object
          type: object
        errors:
          items:
            $ref: '#/components/schemas/ImportFileError'
          type: array
      type: object
    ProjectLocaleStatsDto:
      description: Translation status per language
      example:
        reviewedProgress: 5
        strings: 1
        langCode: langCode
        langName: langName
        reviewed: 5
      properties:
        langCode:
          description: Language code (ie `en` or `en-US`)
          type: string
        langName:
          description: Language name (ie `English` or `English (US)`)
          type: string
        strings:
          description: Total number of string keys in the project
          format: int32
          type: integer
        reviewed:
          description: Number of reviewed string keys for a language
          format: int32
          type: integer
        reviewedProgress:
          description: "Reviewed progress for a language, in percentage"
          format: int32
          type: integer
      type: object
    ProjectStatusDto:
      example:
        reviewedProgress: 6
        strings: 0
        languages:
        - reviewedProgress: 5
          strings: 1
          langCode: langCode
          langName: langName
          reviewed: 5
        - reviewedProgress: 5
          strings: 1
          langCode: langCode
          langName: langName
          reviewed: 5
      properties:
        strings:
          description: Total number of string keys in the project
          format: int32
          type: integer
        reviewedProgress:
          description: "Total reviewed progress across all languages, in percentage"
          format: int32
          type: integer
        languages:
          description: Translation status per language
          items:
            $ref: '#/components/schemas/ProjectLocaleStatsDto'
          type: array
      type: object
    importLocalizationFile_request:
      properties:
        file:
          description: "Uploading file. Supported following formats: `Flutter ARB,\
            \ Android XML, iOS strings, iOS stringsdict, Angular XLF, Gettext PO,\
            \ Gettext POT, Java properties, Ruby on Rails yaml, .NET resx, flat json,\
            \ csv, Excel .xlsx, Excel .xls`"
          format: binary
          type: string
      required:
      - file
      type: object
  securitySchemes:
    API auth:
      in: header
      name: X-Api-Token
      type: apiKey
